version: "3.5"

services:

  flask-server:

    build: server/
    container_name: flask-server

    env_file: database.conf
    environment:
      - RABBITMQ_URL=rabbit
      - RABBITMQ_PORT=5672
      
      - POSTGRES_HOST=database
      - PARSER_PORT=5002

    ports:
      - 5000:5000

    depends_on:
      - rabbit
      - database


  parser:

    build: parser/
    container_name: parser-url

    env_file: database.conf
    environment:
      - RABBITMQ_URL=rabbit
      - RABBITMQ_PORT=5672
      
      - POSTGRES_HOST=database
      - PARSER_THREADS=10
      - DEFAULT_DEPTH=2

    ports:
      - 5002:5000

    depends_on:
      - rabbit
      - database


  rabbit:
    container_name: rabbitmq-tasks
    image: rabbitmq:3.8
    # ports:
    #   - 15672:15672


  database:
    container_name: postgres
    image: postgres:12

    env_file: database.conf

    ports:
      - 5432:5432
"""
# if you want to save db
    volumes:
      - db_volume:/var/lib/postgresql


volumes:
  db_volume:
"""